# Generated by Django 4.2.7 on 2025-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_subject_sme_alter_subject_teachers'),
        ('accounts', '0007_alter_customuser_email_alter_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subjects',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Select subjects (required for role=Teacher)', related_name='specialized_teachers', to='batch.subject'),
        ),
    ]
