# Generated by Django 4.2.7 on 2025-11-21 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0007_subject_sme_alter_subject_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(help_text='Enter the full YouTube URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)')),
                ('description', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yt_classes', to='batch.batch')),
            ],
            options={
                'verbose_name': 'YT Class',
                'verbose_name_plural': 'YT Classes',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_id', models.CharField(help_text='VideoSDK Meeting ID', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='batch.batch')),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['-started_at'],
            },
        ),
    ]
