# Generated by Django 4.2.7 on 2025-11-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ytclass',
            name='description',
        ),
    ]
