# Generated by Django 4.2.7 on 2025-11-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_class', '0002_remove_liveclass_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytclass',
            name='youtube_url',
            field=models.URLField(help_text='Enter the full YouTube Live Class URL'),
        ),
    ]
