# Generated by Django 4.2.7 on 2025-11-22 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_subject_sme_alter_subject_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_class', '0003_alter_ytclass_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.chapter', verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.coursecategory', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='ytclass',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.chapter', verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='ytclass',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.coursecategory', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='ytclass',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='batch.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='ytclass',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
