# Generated by Django 4.2.7 on 2025-11-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_alter_study_class_note_alter_study_lecture_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='dpp_make',
        ),
    ]
